### ISSUE TITLE
Nushell vs zsh?

### ISSUE THREAD

**Issue by Robinlovelace** [b-data/jupyterlab-r-docker-stack#1]
I recently switched from `zsh` to `nushell` and am very impressed with the latter, which is more data-driven and even integrates with the Python package Polars. Wondering if you'd consider switching over after taking a quick read of the README, great to see this in any case!

**Comment by benz0li** [comment]
> Wondering if you'd consider switching over after taking a quick read of the README, great to see this in any case!

One may always install pre-built binaries at `~/.local/bin` at user level within the container.

Not sure I will switch from Zsh to Nu because the latter is [not intended to be POSIX compliant](https://www.nushell.sh/book/default_shell.html#setting-nu-as-login-shell-linux-bsd-macos).

**Comment by Robinlovelace** [comment]
Yeah I spotted it's not POSIX compliant, not sure what that means in practice TBH. In any case I'm testing `nushell` in [ddterm](https://github.com/ddterm/gnome-shell-extension-ddterm) rather than making it the default system shell. Glad to see there's a way of adding new stuff in any case, enough for now...
