### ISSUE TITLE
What about including RStudio Server OSE?

### ISSUE THREAD

**Issue by benz0li** [b-data/jupyterlab-r-docker-stack#4]
I have written the following emails to Posit:

```email
From: Olivier Benz <olivier.benz@b-data.ch>
Date: Sunday, 14 April 2024 at 11:02
To: permissions@posit.co <permissions@posit.co>
Cc: JJ Allaire <[redacted]>
Subject: Re:JupyterLab R docker stack: Permission to include RStudio Server OSE

Dear Sir or Madam,

Still looking forward to an answer to my request.

We create our own docker stack, because I was neither happy with the Version-stable Rocker images nor the Jupyter Docker Stacks.

FYI @JJ

Best regards,
Olivier Benz
aka benz0li

https://github.com/quarto-dev/quarto-cli/issues?q=is%3Aissue+author%3Abenz0li
https://github.com/quarto-dev/quarto-cli/pulls?q=is%3Apr+author%3Abenz0li
```

```email
From: Olivier Benz <olivier.benz@b-data.ch>
Date: Monday, 1 April 2024 at 12:58
To: permissions@posit.co <permissions@posit.co>
Subject: Re: JupyterLab R docker stack: Permission to include RStudio Server OSE

Dear Sir or Madam,

The JupyterLab R docker stack is similar to the binder image of the Rocker Project, which has been granted permission to distribute RStudio binaries through their images.

I would love to make RStudio available as an alternative IDE to code-server in my multi-arch (linux/amd64, linux/arm64) JupyterLab R docker stack.

Best regards,
Olivier Benz
```

```email
From: Olivier Benz <olivier.benz@b-data.ch>
Date: Sunday, 17 March 2024 at 10:19
To: permissions@posit.co <permissions@posit.co>
Subject: JupyterLab R docker stack: Permission to include RStudio Server OSE

Dear Sir or Madam,

RStudio Server OSE (incl. Quarto) has been available for Linux AArch64 (aka arm64) for some time.

I would like to include it in our multi-arch (linux/amd64, linux/arm64) JupyterLab R docker stack.
* For further information, see https://github.com/b-data/jupyterlab-r-docker-stack

According to https://posit.co/about/trademark-guidelines/, I kindly ask for your permission to do so.

Thank you for your many years of contributions to open source software.

Best regards,
Olivier Benz
```

Still waiting for a response.

**Comment by benz0li** [comment]
I have asked Posit to reply here and not to my emails.

**Comment by benz0li** [comment]
@jjallaire I have added an option to install RStudio Server OSE for now. See commit https://github.com/b-data/jupyterlab-r-docker-stack/commit/993a5aafa05452549fe896ce73f3e1d23a2650ee.

I am still looking forward to an answer from @rstudio on whether or not I am permitted to include RStudio Server OSE as an alternative IDE to [code-server](https://github.com/coder/code-server) in our pre-built JupyterLab R docker images.

Thank you in advance for your answer.

FYI @jcheng5

**Comment by aisi-inspect** [comment]
Hi @benz0li, apologies this took so long! Yes, we do give you permission to include RStudio Server OSE in the your pre-built JupyterLab R docker images.

**Comment by jjallaire** [comment]
Hi @benz0li, apologies this took so long! Yes, we do give you permission to include RStudio Server OSE in the your pre-built JupyterLab R docker images.

**Comment by benz0li** [comment]
> Hi @benz0li, apologies this took so long! Yes, we do give you permission to include RStudio Server OSE in the your pre-built JupyterLab R docker images.

Thank you, @jjallaire. Highly appreciated.

Once RStudio is included in the image, the following section will be added to the README:

## Trademarks

RStudio® is a trademark of Posit Software, PBC, all rights reserved, and may be registered in the United States Patent and Trademark Office and in other countries.

The use of the trademarked term RStudio® and the distribution of the RStudio binaries through the images hosted on b-data's GitLab Container Registry (`glcr.b-data.ch`) has been granted by explicit permission of Posit Software, PBC. Please review [Posit’s Trademark Guidelines](https://posit.co/about/trademark-guidelines/) and address inquiries about further distribution to [permissions@posit.co](mailto:permissions@posit.co).
